/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExportRunnerRouteImport } from './routes/export-runner'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiSpacesCorsRouteImport } from './routes/api/spaces-cors'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as ApiRenderBundlesRouteImport } from './routes/api/render-bundles'
import { Route as ApiRecording2VoiceReplaceRouteImport } from './routes/api/recording2-voice-replace'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiPersistAssetRouteImport } from './routes/api/persist-asset'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiExtractVideoAudioRouteImport } from './routes/api/extract-video-audio'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiCoursesRouteImport } from './routes/api/courses'
import { Route as ApiComposeActionsRouteImport } from './routes/api/compose-actions'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as AuthenticatedSegmentLabRouteImport } from './routes/_authenticated/segment-lab'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiSyncFeedSplatRouteImport } from './routes/api/sync-feed.$'
import { Route as ApiRenderAgentUpdatesSplatRouteImport } from './routes/api/render-agent-updates.$'
import { Route as ApiPublicRuntimeInfoRouteImport } from './routes/api/public/runtime-info'
import { Route as ApiPublicBundlesRouteImport } from './routes/api/public/bundles'
import { Route as ApiDivStudioUpdatesSplatRouteImport } from './routes/api/div-studio-updates.$'
import { Route as ApiAssetsSplatRouteImport } from './routes/api/assets/$'
import { Route as ApiAppAssetsSplatRouteImport } from './routes/api/app-assets/$'
import { Route as AuthenticatedProjectIdRouteImport } from './routes/_authenticated/project.$id'
import { Route as AuthenticatedEpisodeIdRouteImport } from './routes/_authenticated/episode.$id'
import { Route as AuthenticatedCourseIdRouteImport } from './routes/_authenticated/course.$id'
import { Route as ApiPublicBundlesSplatRouteImport } from './routes/api/public/bundles.$'
import { Route as ApiPublicAssetsSplatRouteImport } from './routes/api/public/assets/$'

const ExportRunnerRoute = ExportRunnerRouteImport.update({
  id: '/export-runner',
  path: '/export-runner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpacesCorsRoute = ApiSpacesCorsRouteImport.update({
  id: '/api/spaces-cors',
  path: '/api/spaces-cors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderBundlesRoute = ApiRenderBundlesRouteImport.update({
  id: '/api/render-bundles',
  path: '/api/render-bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecording2VoiceReplaceRoute =
  ApiRecording2VoiceReplaceRouteImport.update({
    id: '/api/recording2-voice-replace',
    path: '/api/recording2-voice-replace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPersistAssetRoute = ApiPersistAssetRouteImport.update({
  id: '/api/persist-asset',
  path: '/api/persist-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractVideoAudioRoute = ApiExtractVideoAudioRouteImport.update({
  id: '/api/extract-video-audio',
  path: '/api/extract-video-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesRoute = ApiCoursesRouteImport.update({
  id: '/api/courses',
  path: '/api/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComposeActionsRoute = ApiComposeActionsRouteImport.update({
  id: '/api/compose-actions',
  path: '/api/compose-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSegmentLabRoute = AuthenticatedSegmentLabRouteImport.update({
  id: '/segment-lab',
  path: '/segment-lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSyncFeedSplatRoute = ApiSyncFeedSplatRouteImport.update({
  id: '/api/sync-feed/$',
  path: '/api/sync-feed/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderAgentUpdatesSplatRoute =
  ApiRenderAgentUpdatesSplatRouteImport.update({
    id: '/api/render-agent-updates/$',
    path: '/api/render-agent-updates/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRuntimeInfoRoute = ApiPublicRuntimeInfoRouteImport.update({
  id: '/api/public/runtime-info',
  path: '/api/public/runtime-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBundlesRoute = ApiPublicBundlesRouteImport.update({
  id: '/api/public/bundles',
  path: '/api/public/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDivStudioUpdatesSplatRoute =
  ApiDivStudioUpdatesSplatRouteImport.update({
    id: '/api/div-studio-updates/$',
    path: '/api/div-studio-updates/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAssetsSplatRoute = ApiAssetsSplatRouteImport.update({
  id: '/api/assets/$',
  path: '/api/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppAssetsSplatRoute = ApiAppAssetsSplatRouteImport.update({
  id: '/api/app-assets/$',
  path: '/api/app-assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectIdRoute = AuthenticatedProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEpisodeIdRoute = AuthenticatedEpisodeIdRouteImport.update({
  id: '/episode/$id',
  path: '/episode/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourseIdRoute = AuthenticatedCourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBundlesSplatRoute = ApiPublicBundlesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiPublicBundlesRoute,
} as any)
const ApiPublicAssetsSplatRoute = ApiPublicAssetsSplatRouteImport.update({
  id: '/api/public/assets/$',
  path: '/api/public/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/export-runner': typeof ExportRunnerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/export': typeof AuthenticatedExportRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/review': typeof AuthenticatedReviewRoute
  '/segment-lab': typeof AuthenticatedSegmentLabRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/compose-actions': typeof ApiComposeActionsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/export': typeof ApiExportRoute
  '/api/extract-video-audio': typeof ApiExtractVideoAudioRoute
  '/api/health': typeof ApiHealthRoute
  '/api/persist-asset': typeof ApiPersistAssetRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/recording2-voice-replace': typeof ApiRecording2VoiceReplaceRoute
  '/api/render-bundles': typeof ApiRenderBundlesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/spaces-cors': typeof ApiSpacesCorsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/course/$id': typeof AuthenticatedCourseIdRoute
  '/episode/$id': typeof AuthenticatedEpisodeIdRoute
  '/project/$id': typeof AuthenticatedProjectIdRoute
  '/api/app-assets/$': typeof ApiAppAssetsSplatRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/div-studio-updates/$': typeof ApiDivStudioUpdatesSplatRoute
  '/api/public/bundles': typeof ApiPublicBundlesRouteWithChildren
  '/api/public/runtime-info': typeof ApiPublicRuntimeInfoRoute
  '/api/render-agent-updates/$': typeof ApiRenderAgentUpdatesSplatRoute
  '/api/sync-feed/$': typeof ApiSyncFeedSplatRoute
  '/api/public/assets/$': typeof ApiPublicAssetsSplatRoute
  '/api/public/bundles/$': typeof ApiPublicBundlesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/export-runner': typeof ExportRunnerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/export': typeof AuthenticatedExportRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/review': typeof AuthenticatedReviewRoute
  '/segment-lab': typeof AuthenticatedSegmentLabRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/compose-actions': typeof ApiComposeActionsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/export': typeof ApiExportRoute
  '/api/extract-video-audio': typeof ApiExtractVideoAudioRoute
  '/api/health': typeof ApiHealthRoute
  '/api/persist-asset': typeof ApiPersistAssetRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/recording2-voice-replace': typeof ApiRecording2VoiceReplaceRoute
  '/api/render-bundles': typeof ApiRenderBundlesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/spaces-cors': typeof ApiSpacesCorsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/course/$id': typeof AuthenticatedCourseIdRoute
  '/episode/$id': typeof AuthenticatedEpisodeIdRoute
  '/project/$id': typeof AuthenticatedProjectIdRoute
  '/api/app-assets/$': typeof ApiAppAssetsSplatRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/div-studio-updates/$': typeof ApiDivStudioUpdatesSplatRoute
  '/api/public/bundles': typeof ApiPublicBundlesRouteWithChildren
  '/api/public/runtime-info': typeof ApiPublicRuntimeInfoRoute
  '/api/render-agent-updates/$': typeof ApiRenderAgentUpdatesSplatRoute
  '/api/sync-feed/$': typeof ApiSyncFeedSplatRoute
  '/api/public/assets/$': typeof ApiPublicAssetsSplatRoute
  '/api/public/bundles/$': typeof ApiPublicBundlesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/export-runner': typeof ExportRunnerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/segment-lab': typeof AuthenticatedSegmentLabRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/compose-actions': typeof ApiComposeActionsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/export': typeof ApiExportRoute
  '/api/extract-video-audio': typeof ApiExtractVideoAudioRoute
  '/api/health': typeof ApiHealthRoute
  '/api/persist-asset': typeof ApiPersistAssetRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/recording2-voice-replace': typeof ApiRecording2VoiceReplaceRoute
  '/api/render-bundles': typeof ApiRenderBundlesRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/spaces-cors': typeof ApiSpacesCorsRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/course/$id': typeof AuthenticatedCourseIdRoute
  '/_authenticated/episode/$id': typeof AuthenticatedEpisodeIdRoute
  '/_authenticated/project/$id': typeof AuthenticatedProjectIdRoute
  '/api/app-assets/$': typeof ApiAppAssetsSplatRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/div-studio-updates/$': typeof ApiDivStudioUpdatesSplatRoute
  '/api/public/bundles': typeof ApiPublicBundlesRouteWithChildren
  '/api/public/runtime-info': typeof ApiPublicRuntimeInfoRoute
  '/api/render-agent-updates/$': typeof ApiRenderAgentUpdatesSplatRoute
  '/api/sync-feed/$': typeof ApiSyncFeedSplatRoute
  '/api/public/assets/$': typeof ApiPublicAssetsSplatRoute
  '/api/public/bundles/$': typeof ApiPublicBundlesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/export-runner'
    | '/admin'
    | '/compose'
    | '/courses'
    | '/export'
    | '/projects'
    | '/review'
    | '/segment-lab'
    | '/api/admin'
    | '/api/auth'
    | '/api/compose-actions'
    | '/api/courses'
    | '/api/export'
    | '/api/extract-video-audio'
    | '/api/health'
    | '/api/persist-asset'
    | '/api/projects'
    | '/api/recording2-voice-replace'
    | '/api/render-bundles'
    | '/api/reviews'
    | '/api/spaces-cors'
    | '/api/sync'
    | '/api/transcribe'
    | '/api/tts'
    | '/course/$id'
    | '/episode/$id'
    | '/project/$id'
    | '/api/app-assets/$'
    | '/api/assets/$'
    | '/api/div-studio-updates/$'
    | '/api/public/bundles'
    | '/api/public/runtime-info'
    | '/api/render-agent-updates/$'
    | '/api/sync-feed/$'
    | '/api/public/assets/$'
    | '/api/public/bundles/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/export-runner'
    | '/admin'
    | '/compose'
    | '/courses'
    | '/export'
    | '/projects'
    | '/review'
    | '/segment-lab'
    | '/api/admin'
    | '/api/auth'
    | '/api/compose-actions'
    | '/api/courses'
    | '/api/export'
    | '/api/extract-video-audio'
    | '/api/health'
    | '/api/persist-asset'
    | '/api/projects'
    | '/api/recording2-voice-replace'
    | '/api/render-bundles'
    | '/api/reviews'
    | '/api/spaces-cors'
    | '/api/sync'
    | '/api/transcribe'
    | '/api/tts'
    | '/course/$id'
    | '/episode/$id'
    | '/project/$id'
    | '/api/app-assets/$'
    | '/api/assets/$'
    | '/api/div-studio-updates/$'
    | '/api/public/bundles'
    | '/api/public/runtime-info'
    | '/api/render-agent-updates/$'
    | '/api/sync-feed/$'
    | '/api/public/assets/$'
    | '/api/public/bundles/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/export-runner'
    | '/_authenticated/admin'
    | '/_authenticated/compose'
    | '/_authenticated/courses'
    | '/_authenticated/export'
    | '/_authenticated/projects'
    | '/_authenticated/review'
    | '/_authenticated/segment-lab'
    | '/api/admin'
    | '/api/auth'
    | '/api/compose-actions'
    | '/api/courses'
    | '/api/export'
    | '/api/extract-video-audio'
    | '/api/health'
    | '/api/persist-asset'
    | '/api/projects'
    | '/api/recording2-voice-replace'
    | '/api/render-bundles'
    | '/api/reviews'
    | '/api/spaces-cors'
    | '/api/sync'
    | '/api/transcribe'
    | '/api/tts'
    | '/_authenticated/course/$id'
    | '/_authenticated/episode/$id'
    | '/_authenticated/project/$id'
    | '/api/app-assets/$'
    | '/api/assets/$'
    | '/api/div-studio-updates/$'
    | '/api/public/bundles'
    | '/api/public/runtime-info'
    | '/api/render-agent-updates/$'
    | '/api/sync-feed/$'
    | '/api/public/assets/$'
    | '/api/public/bundles/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExportRunnerRoute: typeof ExportRunnerRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiComposeActionsRoute: typeof ApiComposeActionsRoute
  ApiCoursesRoute: typeof ApiCoursesRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiExtractVideoAudioRoute: typeof ApiExtractVideoAudioRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPersistAssetRoute: typeof ApiPersistAssetRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiRecording2VoiceReplaceRoute: typeof ApiRecording2VoiceReplaceRoute
  ApiRenderBundlesRoute: typeof ApiRenderBundlesRoute
  ApiReviewsRoute: typeof ApiReviewsRoute
  ApiSpacesCorsRoute: typeof ApiSpacesCorsRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiAppAssetsSplatRoute: typeof ApiAppAssetsSplatRoute
  ApiAssetsSplatRoute: typeof ApiAssetsSplatRoute
  ApiDivStudioUpdatesSplatRoute: typeof ApiDivStudioUpdatesSplatRoute
  ApiPublicBundlesRoute: typeof ApiPublicBundlesRouteWithChildren
  ApiPublicRuntimeInfoRoute: typeof ApiPublicRuntimeInfoRoute
  ApiRenderAgentUpdatesSplatRoute: typeof ApiRenderAgentUpdatesSplatRoute
  ApiSyncFeedSplatRoute: typeof ApiSyncFeedSplatRoute
  ApiPublicAssetsSplatRoute: typeof ApiPublicAssetsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/export-runner': {
      id: '/export-runner'
      path: '/export-runner'
      fullPath: '/export-runner'
      preLoaderRoute: typeof ExportRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spaces-cors': {
      id: '/api/spaces-cors'
      path: '/api/spaces-cors'
      fullPath: '/api/spaces-cors'
      preLoaderRoute: typeof ApiSpacesCorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render-bundles': {
      id: '/api/render-bundles'
      path: '/api/render-bundles'
      fullPath: '/api/render-bundles'
      preLoaderRoute: typeof ApiRenderBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recording2-voice-replace': {
      id: '/api/recording2-voice-replace'
      path: '/api/recording2-voice-replace'
      fullPath: '/api/recording2-voice-replace'
      preLoaderRoute: typeof ApiRecording2VoiceReplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/persist-asset': {
      id: '/api/persist-asset'
      path: '/api/persist-asset'
      fullPath: '/api/persist-asset'
      preLoaderRoute: typeof ApiPersistAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-video-audio': {
      id: '/api/extract-video-audio'
      path: '/api/extract-video-audio'
      fullPath: '/api/extract-video-audio'
      preLoaderRoute: typeof ApiExtractVideoAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses': {
      id: '/api/courses'
      path: '/api/courses'
      fullPath: '/api/courses'
      preLoaderRoute: typeof ApiCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compose-actions': {
      id: '/api/compose-actions'
      path: '/api/compose-actions'
      fullPath: '/api/compose-actions'
      preLoaderRoute: typeof ApiComposeActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/segment-lab': {
      id: '/_authenticated/segment-lab'
      path: '/segment-lab'
      fullPath: '/segment-lab'
      preLoaderRoute: typeof AuthenticatedSegmentLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/sync-feed/$': {
      id: '/api/sync-feed/$'
      path: '/api/sync-feed/$'
      fullPath: '/api/sync-feed/$'
      preLoaderRoute: typeof ApiSyncFeedSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render-agent-updates/$': {
      id: '/api/render-agent-updates/$'
      path: '/api/render-agent-updates/$'
      fullPath: '/api/render-agent-updates/$'
      preLoaderRoute: typeof ApiRenderAgentUpdatesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/runtime-info': {
      id: '/api/public/runtime-info'
      path: '/api/public/runtime-info'
      fullPath: '/api/public/runtime-info'
      preLoaderRoute: typeof ApiPublicRuntimeInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bundles': {
      id: '/api/public/bundles'
      path: '/api/public/bundles'
      fullPath: '/api/public/bundles'
      preLoaderRoute: typeof ApiPublicBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/div-studio-updates/$': {
      id: '/api/div-studio-updates/$'
      path: '/api/div-studio-updates/$'
      fullPath: '/api/div-studio-updates/$'
      preLoaderRoute: typeof ApiDivStudioUpdatesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$': {
      id: '/api/assets/$'
      path: '/api/assets/$'
      fullPath: '/api/assets/$'
      preLoaderRoute: typeof ApiAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-assets/$': {
      id: '/api/app-assets/$'
      path: '/api/app-assets/$'
      fullPath: '/api/app-assets/$'
      preLoaderRoute: typeof ApiAppAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/project/$id': {
      id: '/_authenticated/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AuthenticatedProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/episode/$id': {
      id: '/_authenticated/episode/$id'
      path: '/episode/$id'
      fullPath: '/episode/$id'
      preLoaderRoute: typeof AuthenticatedEpisodeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course/$id': {
      id: '/_authenticated/course/$id'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof AuthenticatedCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bundles/$': {
      id: '/api/public/bundles/$'
      path: '/$'
      fullPath: '/api/public/bundles/$'
      preLoaderRoute: typeof ApiPublicBundlesSplatRouteImport
      parentRoute: typeof ApiPublicBundlesRoute
    }
    '/api/public/assets/$': {
      id: '/api/public/assets/$'
      path: '/api/public/assets/$'
      fullPath: '/api/public/assets/$'
      preLoaderRoute: typeof ApiPublicAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSegmentLabRoute: typeof AuthenticatedSegmentLabRoute
  AuthenticatedCourseIdRoute: typeof AuthenticatedCourseIdRoute
  AuthenticatedEpisodeIdRoute: typeof AuthenticatedEpisodeIdRoute
  AuthenticatedProjectIdRoute: typeof AuthenticatedProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSegmentLabRoute: AuthenticatedSegmentLabRoute,
  AuthenticatedCourseIdRoute: AuthenticatedCourseIdRoute,
  AuthenticatedEpisodeIdRoute: AuthenticatedEpisodeIdRoute,
  AuthenticatedProjectIdRoute: AuthenticatedProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicBundlesRouteChildren {
  ApiPublicBundlesSplatRoute: typeof ApiPublicBundlesSplatRoute
}

const ApiPublicBundlesRouteChildren: ApiPublicBundlesRouteChildren = {
  ApiPublicBundlesSplatRoute: ApiPublicBundlesSplatRoute,
}

const ApiPublicBundlesRouteWithChildren =
  ApiPublicBundlesRoute._addFileChildren(ApiPublicBundlesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExportRunnerRoute: ExportRunnerRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiComposeActionsRoute: ApiComposeActionsRoute,
  ApiCoursesRoute: ApiCoursesRoute,
  ApiExportRoute: ApiExportRoute,
  ApiExtractVideoAudioRoute: ApiExtractVideoAudioRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPersistAssetRoute: ApiPersistAssetRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiRecording2VoiceReplaceRoute: ApiRecording2VoiceReplaceRoute,
  ApiRenderBundlesRoute: ApiRenderBundlesRoute,
  ApiReviewsRoute: ApiReviewsRoute,
  ApiSpacesCorsRoute: ApiSpacesCorsRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiAppAssetsSplatRoute: ApiAppAssetsSplatRoute,
  ApiAssetsSplatRoute: ApiAssetsSplatRoute,
  ApiDivStudioUpdatesSplatRoute: ApiDivStudioUpdatesSplatRoute,
  ApiPublicBundlesRoute: ApiPublicBundlesRouteWithChildren,
  ApiPublicRuntimeInfoRoute: ApiPublicRuntimeInfoRoute,
  ApiRenderAgentUpdatesSplatRoute: ApiRenderAgentUpdatesSplatRoute,
  ApiSyncFeedSplatRoute: ApiSyncFeedSplatRoute,
  ApiPublicAssetsSplatRoute: ApiPublicAssetsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
